### ISSUE TITLE
Lost SSH recently

### ISSUE THREAD

**Issue by alexj212** [marcosscriven/galeforce#10]
Has anyone else lost ssh? The unit still shows dev mode being purple, but I have lost ssh. Was there a recent update that took it away.

**Comment by jofan** [comment]
I just set one up with 0.5 and got access to SSH. Google Wifi is version 9334.41.3 which is the second most recent. It'll be interesting to see if SSH is lost with 9765.65.2.

**Comment by alexj212** [comment]
Mine was auto upgraded to 9765.65.2 when I lost ssh. The color is still purple though.

**Comment by jofan** [comment]
It just got updated and I still got SSH. Did you change the password?

**Comment by alexj212** [comment]
I did change password - Its no longer listening on port 22.

**Comment by northvibe** [comment]
I just received my G wifi and was trying to do this root. I couldn't get ssh access either. I checked and I was on the 9334.x version, but via nmap scanning ports, ssh was not allowed.

**Comment by mlinton** [comment]
Can anyone confirm that this still works with the latest google wifi firmware - 11021.84.4

**Comment by javanator** [comment]
@mlinton I did a new install. Confirmed working and then after the update to 11021.84.4 no more. 

So i'm confirming the latest update killed (my) ssh access.
