### ISSUE TITLE
Is this project not working anymore?

### ISSUE THREAD

**Issue by alekslyse** [marcosscriven/galeforce#13]
I tried exactly due to the description to install galeforce on a Google WIFI, and everything seem to be working, except the SSH. 

I started by restoring with the restore instructions, then installed gale with an image created with the recovery tool. Looking at the logs it seems busybox etc was copied, and after starting and setting up the wifi it settles on a purple color - but no SSH. So maybe the fun is over?

Logs from the USB attached to this post

[spinner.log](https://github.com/marcosscriven/galeforce/files/1522684/spinner.log)
[recovery.log](https://github.com/marcosscriven/galeforce/files/1522685/recovery.log)

**Comment by murphster47** [comment]
having same issue.. version 9460.40.5

**Comment by alekslyse** [comment]
I got it working by using the premade bin (though I dont know if that caused the issue). 

After trying 30 times what worked was

1. Make sure all WIFI points and APP are reset
2. Flash the master based on the instructions given (0.5)
3. When it stops flashing purple and are steady purple setup the WIFI with the app with master only - do NOT update.
4. Connect to the master via SSH and change the password - reconnect to verify the password got updated.
5. Connect the first MESH point to the network.
6. Do NOT update via the app
7. Enable Telnet as a secondary connection 

For me, when doing it like that the SSH and Telnet has kept active updating from the base version that I flashed all to the now current 9901.54.2 - the one that let you change IP and DHCP range in the app. Looks like the trick is to let it update in automatically, not via the app.

**Comment by EagerFace** [comment]
I intended on following this method, except after flashing the master and setting up in the app, I wasn't able to connect with SSH even once to reset the password. I was on version 9334.41.3 after the flash.

**Comment by guner1907** [comment]
Hey folks,

I did the below steps and still couldn't get root access to GWiFi;

1- Created the Gale Image from scratch within Linux environment with marcos's script.
2- Created the USB Image from OnHub Recovery Tool from Chrome with using new gale image that i created.
3- Followed the instruction and applied the image to GWiFi
4- When everything finishes i configured the GWiFi without any problem (only i noticed that the light now in purple instead of blue, i believe it's related to the Gale image)
5- When i try to access to the GWiFi through ssh or telnet, i always receives connection refused, i believe some how GWiFi has a default fw rule which blocks the communication on ssh or telnet.

When i created the gale image and applied it, i noticed that the firmware version 9901.53.2 and after a while GWiFi upgraded itself to 10032.86.0. and for sure the other 2 GWiFi which i use in mesh configuration.

I only applied the gale image to the main GWiFi.

Can someone share his/her experience if they successfully had a root access.

Thanks.

**Comment by RyanEwen** [comment]
Bump. Is this working for anyone else?

**Comment by alekslyse** [comment]
I think google did something with the latest update, as I just upgraded a new google wifi with the built v0.5, and when its booting the first time SSH is working, but when it update itself to the latest version SSH is blocked. 

Anyone with SSH that upgraded to the latest current that still have SSH (or telnet)?

**Comment by somewhat-random** [comment]
For anyone interested, I was able to successfully root my Google WiFi, running the latest update, 10032.86.2.  

The trick, for me, was that my device did NOT take on the IP address stated in the readme.  The readme states that you should ssh to 192.168.86.1.  After rooting, my GW began pulsing purple and picked up the IP 192.168.84.1, I believe.  I have no information as to why...

To find it, I rebooted the GW point while my PC was connected to the LAN port and I watched the interface with Wireshark.  A short while in, the GW popped out some traffic from its IP.  I could ssh to that address immediately.  From there, all was normal.

**Comment by cvccole** [comment]
So the only thing that changed was the IP that worked for ssh??

**Comment by somewhat-random** [comment]
This was my first time through, but that was the only missing piece for me.

**Comment by bbong718** [comment]
Was anyone able to get OpenVPN running on Google WIFI?

**Comment by cvccole** [comment]
Nope

**Comment by bbong718** [comment]
We are close with full tutorial. 🤗

**Comment by northvibe** [comment]
I'm having issues getting this to function. Even with the root image, ssh was blocked. The Gwifi sat for a while and updated itself, now I can't even flash the recovery image. I get into the purple blink, but when plugging in a usb to flash, it goes to flashing orange.

**Comment by dherby** [comment]
After google update google wifi to 10718.111.0 sshd has been blocked.
I still have my configuration working properly (Forwared DNS and dnsmasq tweaks) but tcp port 22 is closed. Impossible to connect anymore via ssh.

Any idea ?


```Starting Nmap 6.47 ( http://nmap.org ) at 2018-12-13 04:18 CET
Nmap scan report for 192.168.86.1
Host is up (1.0s latency).
Not shown: 995 closed ports
PORT     STATE SERVICE
53/tcp   open  domain
80/tcp   open  http
5000/tcp open  upnp
8080/tcp open  http-proxy
8081/tcp open  blackice-icecap

Nmap done: 1 IP address (1 host up) scanned in 7.28 seconds```

**Comment by northvibe** [comment]
Yes, I had the same thing. 

The only thing I'm thinking is being able to flash to a prior firmware, do the mod. Not sure how we get that old version though?

**Comment by dherby** [comment]
I tried it yesterday without success. I'd rolled back to version 9334.41.3 with OnHub (Succefuly) and then I'd been able to install galeforce without issue.  Nonetheless, when the GWifi update itself to 10718.111.0 I lost connection :(

**Comment by northvibe** [comment]
Is there a way to allow a port or forward before it updates itself? With internet access, it will self update. If we have a way to block gwifi from updating that would be helpful. I'm trying to use this as a project so I don't need it to be updated.

**Comment by mlinton** [comment]
Can anyone confirm that they've been able to use this hack on the latest firmware from google?  I don't think people will be willing to go down this path if they aren't able to SSH into the router.  Maybe there is a way to change the port that it's listening on?

**Comment by eugene2005** [comment]
I am having same issue. Flashed galeforce no problem, could ssh without an issue but once I started an app to setup my WiFi mesh Google WiFi updated firmware to the latest version and I cannot longer ssh (connection refused)

**Comment by stefanboenders** [comment]
Same problem here. I'm running version 11021.84.4

**Comment by americanslon** [comment]
Same version, same problem.  Any news?

**Comment by stefanboenders** [comment]
At the moment my gwifi is flashing red. I a factory reset several times, but it's not working anymore at all. Anyone else having the same issue?

**Comment by americanslon** [comment]
Same, I thought mine croaked but now i think its the firmware. I had to put in another puck as main to get things to come back. Anyone knows where to get the original firmware?

**Comment by 3boysdad** [comment]
@americanslon - that's a good question...i'd like to get my hands on it too.
