### ISSUE TITLE
able to ssh and passwd, now what?

### ISSUE THREAD

**Issue by drewmullen** [marcosscriven/galeforce#14]
how do i get this thing to work as a regular router again? router is flashing purple after applying update (still in dev mode, right?). I was able to ssh as root and passwd. 

After applying the image from the flash drive i unplugged the usb, and brought it back to the modem (did the patch from a different room). after replugging the router back into the modem its still flashing purple and is not router internet traffic. 

Is there another step i need to follow? Does the usb need to stay plugged in? Do i need to 'factory reset' the wifi points from the google home app (i was using these as regular mesh routers before applying galeforce)?

**Comment by drewmullen** [comment]
All i had to do was 'reset' the access points in my google wifi app and have the app find the device again... didnt have to leave developer mode, leave the usb in, or anything like that

**Comment by gsshelton** [comment]
Curious as to what username and password you used to log in once you had SSH? I tried onhub and several other ones, but none work.
