### ISSUE TITLE
How to Block Google DNS?

### ISSUE THREAD

**Issue by ghost** [marcosscriven/galeforce#17]
Hello I want to know is there any way to block DNS on Google Wifi

I was reading posts that said it can be block by setting Static Routes on the router.

Can someone confirm if this can be done after installing Galeforce on it?

**Comment by idvoretskyi** [comment]
@JdRssll not sure about blocking, but you should be able to select a different DNS provider in the app menu ([screenshot](https://imgur.com/Fyl8bfI)).
