### ISSUE TITLE
Is this reversible? If it is, please document the process

### ISSUE THREAD

**Issue by Bluebie** [marcosscriven/galeforce#2]
I'd like to explore galeforce, but i want to confirm there's some way to completely reverse the process and get back to a factory state.

**Comment by marcosscriven** [comment]
Hi @Bluebie 

Yes it's easily revertible - I've [outlined the steps here](https://github.com/marcosscriven/galeforce/wiki/How-to-reset-to-normal-mode). Let me know if you need any more info.

**Comment by lycca** [comment]
Hi Marcos, I failed to restore by recovery mode, could you help to see the link below and advise what I can do, many thanks.

https://groups.google.com/a/chromium.org/forum/m/?hl=en#!topic/chromium-os-dev/98yOPE3UEBo
