### ISSUE TITLE
How to reset back to default

### ISSUE THREAD

**Issue by ghost** [marcosscriven/galeforce#21]
How do you uninstall galeforce after installing it?

**Comment by ghostivv** [comment]
If still stuck, then follow google's recovery process. Just done mine as I couldn't access ssh but the wifi were working fine. Think mine got stuck on developer's mode. 

https://support.google.com/wifi/answer/6274977?hl=en

**Comment by ghost** [comment]
The OnHub Recovery Utility will also work on the Google Wifi?

**Comment by ghostivv** [comment]
When you get to image download page, you'll have option for google wifi as well.

**Comment by ghost** [comment]
Oh, thank you! Around how long did it take you to restore your unit?

**Comment by ghostivv** [comment]
Not sure but around 10-13 mins. Just follow instructions and should be ok. On mine when writing image  to USB failed on first try but went through on 2nd attempt. Apart that smooth sailing :-)

**Comment by ghost** [comment]
Got it. Thank you!

**Comment by stefanboenders** [comment]
I used the recovery tool but noticed my wifi is still flashing purple (galeforce). Anyone successfully reverted galeforce?

**Comment by magic-madrigal** [comment]
Yes, I was able to revert my Google Wifi pretty easily following this wiki
page.

https://github.com/marcosscriven/galeforce/wiki/How-to-reset-to-normal-mode

Although the Google Help page states that the OnHub recovery tool doesn't
support Google Wifi, it's not true and probably just outdated.
