### ISSUE TITLE
After rooting, historical usage not being captured

### ISSUE THREAD

**Issue by somewhat-random** [marcosscriven/galeforce#24]
After rooting, I seem to be missing historical traffic data from my device and network page.  

When I load the "usage" pages in the Google WiFi app, the realtime stats work fine - showing instant throughput in kbps or Mbps for each device, and for the network overall.  Great.

However, when I hit the drop down for "1 day", "7 days", or longer, I get 0KB Total Download, 0KB Total Upload for every device and also for the whole network.  And, no bars at all on the charts to the beginning of time.

- Has anyone else had this issue after rooting?  
- Is the data kept anywhere on the wifi point where I can verify it's being collected?
- Is this data uploaded to Google for the app's use, or is it fetched realtime off of the wifi point?

**Comment by gcochard** [comment]
I see this issue too. I'll see if I can track it down.
