### ISSUE TITLE
vbutil_kernel binary command not found

### ISSUE THREAD

**Issue by cremion** [marcosscriven/galeforce#25]
In the process of running the build-all shell script, I have found that the script is unable to execute the vbutil_kernel command as it is not found. 

Is this binary obtainable as ANY one of the following?
- yum package
- deb package
- rpm package
- tarball 

TIA

**Comment by phillipmcmahon** [comment]
For debian take a look here. Installs, /usr/bin/vbutil_kernel

https://packages.debian.org/sid/vboot-kernel-utils
