### ISSUE TITLE
Possible to add DHCP client options

### ISSUE THREAD

**Issue by phillipmcmahon** [marcosscriven/galeforce#26]
Hi,

Before I take the plunge and root my device I was hoping to know if post-root I will then be able to amend my DHCP client ID that is sent out when an IP is requested.

The reason being is my ISP requires a custom string to be sent before it assigns an ISP. It also requires the interface to be in VLAN ID 10 but I can use a managed switch to append this to the interface. Unless someone can help me in defining the VLAN ID for the WAN interface natively.

The client option I need to send is vendor-class-identifier with a value of "100008,0001"

Appreciate any and all input.

Thanks in advance.

**Comment by somewhat-random** [comment]
I believe Gwifi uses dnsmasq for its DHCP handling. If dnsmasq can offer that identifier then you can configure GWifi to do so.
