### ISSUE TITLE
Bridge mode with mesh network functionality

### ISSUE THREAD

**Issue by mav2287** [marcosscriven/galeforce#28]
Being able to bridge GWF while still using the wireless mesh seems to be something that GWF won’t do out of the box, but a lot of people wish it would do. Is there a way to do this using gale force?

**Comment by myusuf3** [comment]
Would love to see this too.

**Comment by myusuf3** [comment]
@mav2287 you get something working?

**Comment by boywiz** [comment]
Any news on this i am seriously contemplating ditching this Google Wifi :( units for some Linksys Velop units purely cause of this bridge mode issue.

Have you seen this as well if not please sign it too we may just get what we want https://www.change.org/p/google-inc-google-wifi-allow-mesh-in-bridge-mode

**Comment by mav2287** [comment]
I think at this point this has been beat to death and is just a hope/dream we won't see come true.
