### ISSUE TITLE
Solid Purple But No SSH?

### ISSUE THREAD

**Issue by veritas06** [marcosscriven/galeforce#3]
I'm sorry if this is the wrong spot, but hopefully just a quick question: I followed all your steps, everything seemed to go as expected. I now have a solid Purple light on (assuming that's just a notification that the device is in Developer Mode, like bootloader unlock notifications) but I'm not able to SSH. Just getting Connection Refused. Maybe I did something wrong along the way & need to redo the process?

Thanks in advance for any suggestions.

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by marcosscriven** [comment]
How are you connecting to the device? What's the IP? Does it respond to pings? What version did you try?

**Comment by TheCrach** [comment]
Same issue here, SSH connection refused with solid purple light.
The gateway is not pinging but Internet is working.
I tried the gale.bin 0.5 on my side, seems like a firewall is blocking something.

**Comment by marcosscriven** [comment]
It should be pulsing purple, not solid purple. How did you prepare the USB stick?

**Comment by marcosscriven** [comment]
@veritas06 @TheCrach  can you try this method to create the USB installer?

https://github.com/marcosscriven/galeforce/wiki/How-to-create-a-USB-installer

It sounds to me like you've got it into developer mode, but the install hasn't worked. In fact, immediately after install the version should have regressed a little (which yours hasn't), as the recovery image is always a bit behind the updates. 

I don't think it's a firewall issue.

**Comment by veritas06** [comment]
Sorry for leaving my version info out. Should have know to include all that initially. Mine was pulsing at the right times that you had in your guide, it was just afterwards that it stayed a solid Purple instead of White. I figured that was the "Developer Mode Active" sign.
I used dd to create the USB stick. I clearly must have messed something up so I'll just go through the process again & see if I can get it done correctly the second time around.

**Comment by marcosscriven** [comment]
Well good luck @veritas06 - would be great to know if you get it working. Note there should be logs written back to the USB stick which you can see if you're familiar with mounting ext partitions.

**Comment by veritas06** [comment]
Okay, great. My main box is Linux, so I'm no stranger terminal, etc, & I was wondering if logs were generated at all during the process.
I'll let you know how it turns out, & just want to thank you for this project. I'm always looking for ways to tweak my device, & this is just one more fun project for me =]

**Comment by marcosscriven** [comment]
One thing to add, once in developer mode (which it sounds like you are), you only need to wait a second or two after startup (for the blue to change to flashing purple), before hitting the bubble switch to boot from USB.

**Comment by TheCrach** [comment]
Just used the OnHub recovery utility, did the same process and got it working (my USB drive was flashing and the "blackout" lasted way longer than before), I also used dd to create my USB disk in the first place.

![img_0421](https://user-images.githubusercontent.com/5264048/28498488-ebd5542a-6f9e-11e7-9d00-455a49bea81f.JPG)

Thank you for all the work !

**Comment by veritas06** [comment]
Sweet! Finally able to get it up & running! I followed the same path as @TheCrach & used the onHub Restore Utility (after seeing it not work on Linux, then Windows, finally ended up on macOS) & after that it was smooth sailing.

So if anyone else has the same issue & finds this thread: Use the onHub Restore Utility from the Chrome Web Store to get the USB drive formatted \ configured correctly.\

Thanks again @marcosscriven !!

**Comment by veritas06** [comment]
For got to close the issue in my last post, so re-doing it here

Sweet! Finally able to get it up & running! I followed the same path as @TheCrach & used the onHub Restore Utility (after seeing it not work on Linux, then Windows, finally ended up on macOS) & after that it was smooth sailing.

So if anyone else has the same issue & finds this thread: Use the onHub Restore Utility from the Chrome Web Store to get the USB drive formatted \ configured correctly.\

Thanks again @marcosscriven !!

**Comment by mdlima** [comment]
Hey, just recently updated mine and got it working (tahnks @marcosscriven, awesome work!).

However, I get the solid purple light and I was wondering if this is the expected behavior or if I ended up in dev mode and should restore and reapply as stated here.

Thanks

**Comment by veritas06** [comment]
I've had the purple since going through this & just figured it was expected & the device's way of showing Dev Mode.
