### ISSUE TITLE
sadness...

### ISSUE THREAD

**Issue by 3boysdad** [marcosscriven/galeforce#30]
so... a few questions...

first...which binaries should be placed on the USB...  the gz file(s) or tar file(s) which one(s) galeforce or gale.bin?

second...(even with all four files on the USB)..this doesn't seem to work...

Wait until device restarts and starts blinking purple again
Plug in USB stick
Hit bubble switch again <- no restart here....just continues to blink purple.

**Comment by 3boysdad** [comment]
sigh...i'm a moron...please move along...nothing to see here other than someone's ignorance...  anyone tripping across this...read the wiki...especially page 2...

**Comment by cvccole** [comment]
I had the same problem and figured this would not work.

**Comment by 3boysdad** [comment]
well to be fair...i did get it work...my main unit is staring at me with a purple LED, waiting for me to command.
