### ISSUE TITLE
OpenVPN

### ISSUE THREAD

**Issue by funktafide** [marcosscriven/galeforce#31]
Does anyone have a guide for getting OpenVPN set up after root? Ive looked over the Gentoo guides for doing this, but none of the commands used are available inside of the Gentoo installed on the puck.  emerge doesn't exist, I can't scp files over to copy the OpenVPN files if I wanted to manually install.  No text editors show up for modifying the ssh_config.  Im still a bit of a noob with bash, so maybe Im missing something.  Would like to get a VPN client up and running on my main puck.  Any help would be appreciated.

**Comment by muffstic** [comment]
I think I finally achieved root, but now I also need to know how to install a VPN.

**Comment by funktafide** [comment]
I definitely have root, but can't find a good guide for installing OpenVPN on Gentoo.  If you can SSH to the device, then your root is good.  The Gentoo build on there doesn't have any type of package installer and I haven't been able to figure out how to transfer over with WinSCP.  It doesn't accept the transfers.  If you could get a transfer through, then you should be able to send the tar files for OpenVPN over to it.

**Comment by Farslasher** [comment]
Any update on a guide to install openvpn?
