### ISSUE TITLE
DynDNS...

### ISSUE THREAD

**Issue by 3boysdad** [marcosscriven/galeforce#32]
Ok...i'll admit I am kind of a n00b when it comes to Unix.   In the past, when working with DD-WRT, I've been able to find my way around most of my issues using my Google skills.  However, alas this has me stumped.  I have a shell script that calls out DNS-o-Matic which then can update OpenDNS with my dynamic IP provided by my ISP.

In poking around the processes and reading about the lack of a CRON process I ran into this gem called - periodic_scheduler - which appears do what I want.  Essentially it calls a shell script on a timer.  And after looking at the running processes on my device I can see this is already happily running _and_ running several processed at various intervals.

So the question...does anyone know how to add a new script for periodic_scheduler to execute?

**Comment by tctree333** [comment]
Did you successfully get the ssh access? I've just stumbled upon this and I can't seem to get this to work. I successfully got in, but after unplugging it then plugging it back in, I lost the ssh access and it said: "Connection Refused". I'm running version 10452.90.5.

**Comment by 3boysdad** [comment]
Yep still have SSH, otherwise I'd not be able  to see the running process via the top command
