### ISSUE TITLE
Will this let me make gwifi set DNS for dhcp clients to its' custom DNS?

### ISSUE THREAD

**Issue by jherman** [marcosscriven/galeforce#33]
Not so much an issue, as a general question.  I'm using pihole software to filter ads. With the way gwifi is today, I added pihole's IP as the first DNS entry.   Apparently gwifi still hands out 192.168.86.1 as the DNS to DHCP clients instead of pihole's IP.  Is this something that can be fixed if I root it?

[EDIT]
I should note that, yes I do know that pihole will still work, however, I will only see one IP (that of gwifi) in the dashboard, instead of seeing all individual client IP's that ask for DNS requests.

**Comment by Geczy** [comment]
# EDIT 2/4/2019:

These steps have now been automated on my fork https://github.com/Geczy/galeforce



---

#9 # Advertise Pi-hole’s IP address via dnsmasq in the router

This is the preferred method as stated by pi-hole's wiki

It's pretty simple, follow my guide below. This essentially follows the setup instructions [from here](https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server/245), method 2. The Gwifi app disables configuring dnsmasq, but once you're rooted you can modify it manually through ssh.


## Features

* Maintains the Gwifi mesh network
* Per-host tracking on Pi-hole
* Gwifi app shows clients
* Gwifi app is the primary for port forwarding and managing the wifi
* The ability to resolve hostnames on the LAN
* Ad blocking/network monitoring provided by Pi-hole

## Requirements

* Gwifi should be rooted
To learn how to root, [follow the readme on my fork](https://github.com/Geczy/galeforce/blob/master/README.md), it's the most updated and comprehensive one
* Gwifi should not be in bridge mode
* Gwifi should be the primary dhcp server
* The raspberry pi should be assigned a static IP through the Gwifi app
* Do not setup upstream dns servers on pi-hole
* Do not enable dhcp server on pi-hole

## Guide

```bash
ssh root@192.168.86.1 # login to the router as root
cp /etc/init/dnsmasq.conf /usr/local/galeforce/data # save a backup
vi /etc/init/dnsmasq.conf # modify the original 
## after making the modifications listed below:
sudo reboot # reboot AFTER mods 
```

Find each of these lines:

```bash
dhcp-option=${LAN_BRIDGE},6,${SETTING_BRIDGE_ADDRESS}
dhcp-option=${GUEST_BRIDGE},6,${SETTING_GUEST_BRIDGE_ADDRESS}
dhcp-option=${SETUP_LAN_BRIDGE},6,${SETTING_SETUP_LAN_ADDRESS}
```

Replace each line, where 192.168.86.XX is your raspberry pi's IP address

```bash
dhcp-option=${LAN_BRIDGE},6,192.168.86.XX
dhcp-option=${GUEST_BRIDGE},6,192.168.86.XX
dhcp-option=${SETUP_LAN_BRIDGE},6,192.168.86.XX
```

## Screenshots

Pi-hole client list

![image](https://user-images.githubusercontent.com/1036968/50452595-fec19a80-0908-11e9-8c74-cf0be8a7f258.png)

Mesh works

![image](https://user-images.githubusercontent.com/1036968/50453775-04bb7980-0911-11e9-85d6-015b6d7818c1.png)

Clients are shown

![image](https://user-images.githubusercontent.com/1036968/50453771-02591f80-0911-11e9-9477-1482172a84b3.png)

**Comment by americanslon** [comment]
Is there a way to get the device names set in GWIFI app (or hostnames) to show up instead of or in addition to IPs?

**Comment by Geczy** [comment]
yes

**Comment by americanslon** [comment]
How?

**Comment by americanslon** [comment]
@Geczy ping

**Comment by Geczy** [comment]
What I do is export it from my hosts file from gwifi, and import it to the ssh of pi manually. If you want to know which file let me know and I can check

**Comment by americanslon** [comment]
Thank you, if you could please @Geczy 

Is this even still possible though - I have followed the instructions and my device doesn't start blinking orange after holding reset. So kind of a problem on step one...:/

Edit:

I got it to go into dev mode. Steps 3 and 4 in the readme should be reversed. 
Hold the reset buttin, plug in the power and continue holding until the orange light.
Seems like the latest update removes ssh though so...

**Comment by Fahmula** [comment]
Is this still a viable options to get Pihole working with GWifi?

**Comment by americanslon** [comment]
This with that latest gwifi update bricked my puck. This also seems like a dead project so I'd be careful.

**Comment by Fahmula** [comment]
Thanks. I'll continue using the Pihole as the DHCP sever although it seems my PC stop showing up in GWifi.

**Comment by dltacube** [comment]
> Thank you, if you could please @Geczy
> 
> Is this even still possible though - I have followed the instructions and my device doesn't start blinking orange after holding reset. So kind of a problem on step one...:/
> 
> Edit:
> 
> I got it to go into dev mode. Steps 3 and 4 in the readme should be reversed.
> Hold the reset buttin, plug in the power and continue holding until the orange light.
> Seems like the latest update removes ssh though so...

Strange because @Geczy just updated his post recently...Are you still able to get into ssh?

**Comment by d8ahazard** [comment]
So, this was closed....this is specifically why I looked for Galeforce. I want to use it to put my Gwifi behind Pfsense, but I sure as hell don't want to brick my whole network in the process. Any confirmation this works would be *immensely* appreciated.
