### ISSUE TITLE
Keep Factory Features

### ISSUE THREAD

**Issue by caj380** [marcosscriven/galeforce#35]
I apologize for creating an issue just to ask this (probably obvious) question, but I could not find it anywhere.
Does flashing this firmware completely erase all the factory features such as mesh networking, the Google Wifi App and other things or does this keep all the same firmware and just add features to it?

Thanks,
Chase

**Comment by cvccole** [comment]
From what I've read it keeps the features and adds to them. Good luck never been able to get it working myself

**Comment by drewmullen** [comment]
It just unlocks root access. All other features are still available

It's very underwhelming because the device is very locked down. Currently,
I don't think anyone has done anything useful (openvpn, etc) after rooting
