### ISSUE TITLE
SSH Root Password

### ISSUE THREAD

**Issue by gsshelton** [marcosscriven/galeforce#39]
I was able to flash the image and get an SSH connection, but when I try to log in as root, it asks for a password. I've tried 'onhub' and several others as well as no password. No joy.

**Comment by eugene2005** [comment]
Default password is "changeme". It's mentioned on flashing instruction page if you read it carefully.

**Comment by gsshelton** [comment]
I'm an idiot. I figured it out earlier today. I was able to get in change the password, Busybox and I'm going to try and install openVPN. Did you end up installing anything? Thanks for the reply!

**Comment by eugene2005** [comment]
I am currently struggling with galeforce being overridden by Google WiFi firmware update. It's says in the description that it should "survive" firmware update but apparently it does not. Something has changed since it was published 2 years ago,
