### ISSUE TITLE
Kernel module patching

### ISSUE THREAD

**Issue by ludwig-v** [marcosscriven/galeforce#4]
Hello !

Thank you again for your work, I'm currently trying to patch the Qualcomm ethernet driver (ess-edma) used by wan0 & lan0 to restore the avaibility to work with VLANs (see: https://github.com/chunkeey/LEDE-IPQ40XX/commit/f4c1345f73bb63d7c5b9acc7e766c18b071c7885)
I cross-compiled the kernel of the Google Wifi and compiled the .ko module from it to replace it in the .bin recovery image (following the way you did)

Unfortunately, it is not working for some reason.
Flashing is working good, the device is booting correctly (flashing purple, ready to reconfigure but no wifi available) then at some point it is flashing with the orange light (probably because wan0 is not up)
I'm able to load my module on your image (using modprobe) but once loaded the Google Wifi is rebooting.

If you have any idea I would love to get some help

I downloaded and compiled the kernel from : https://chromium.googlesource.com/chromiumos/third_party/kernel/+/factory-gale-8743.19.B-chromeos-3.18
I generated the kernel config from your image: [kernelconfig.txt](https://github.com/marcosscriven/galeforce/files/1175026/kernelconfig.txt) 
Compiled patched module: [essedma.zip](https://github.com/marcosscriven/galeforce/files/1175034/essedma.zip)

Thank's

**Comment by marcosscriven** [comment]
Two things:

1. The kernel branch you link is four months behind what's currently on the device:

```
localhost ~ # uname -a
Linux localhost 3.18.0-14565-g46be31c1033f #1 SMP PREEMPT Fri Jun 2 14:42:21 PDT 2017 armv7l ARMv7 Processor rev 5 (v7l) Qualcomm (Flattened Device Tree) GNU/Linux
```
This may be useful? https://github.com/dnschneid/crouton/wiki/Build-chrome-os-kernel-and-kernel-modules

Not sure if that's pending upstreaming from Google's side?

2. I learnt recently the [USB serial module is available](https://groups.google.com/a/chromium.org/forum/m/#!topic/chromium-os-dev/WtR5e5nmTIQ), so if you have a USB serial adapter, and something to read it like a Raspbery Pi or Bluetooth serial adapter (or even, I suppose, another adapter back to USB),  you can output logs to /dev/ttyUSB0 and see what's going on.

**Comment by marcosscriven** [comment]
One other thing - what are you going to do about auto-updates if you get this working? If an update includes a kernel change (which it most likely will), you're faced with the choice of reverting the kernel (which will probably break), or forever rebuilding and deploying.

**Comment by saturnian-tides** [comment]
> One other thing - what are you going to do about auto-updates if you get this working? If an update includes a kernel change (which it most likely will), you're faced with the choice of reverting the kernel (which will probably break), or forever rebuilding and deploying.

That's actually something I've run into with my own kernel module patches. Is there anything that can be set or configured to disable updates? As a work around I can just not connect the device to the internet, which is sufficient for now. The app's out-of-box setup of the device seems to require an internet connection however.  Is there another way to configure the device's SSID and key through the shell?

Thanks
