### ISSUE TITLE
Newest firmware update overwrites galeforce

### ISSUE THREAD

**Issue by handwiper** [marcosscriven/galeforce#40]
I've downloaded the newest gale .5 and flashed it to my Google WiFi, and i can SSH into it, but when i go to set up my network in the app, it updates the firmware and after that, I'm unable to SSH.

**Comment by mvalezy** [comment]
Hi,
Any update on this ? Did anyone managed to keep Galeforce and the new GWifi firmware ?
Thanks,
Matt

**Comment by handwiper** [comment]
Not that I’m aware of

**Comment by 3boysdad** [comment]
...just got the update here...clobbered my network and it may have actually bricked my primary until i can revert the firmware.

**Comment by cawilliamson** [comment]
@3boysdad I've had exactly the same issue - both of my devices are no longer responding to anything. Lots of flashing and the likes but no WiFi broadcasting happening at all.

Does anyone have any idea how we can revert these devices to stock firmware *or* fix Galeforce?

**Comment by 3boysdad** [comment]
Well it seemed that I got working, by reflashing, for about a day.

**Comment by exitdown** [comment]
yep certainly seems to be a persistence issue. I went thru a heck of a learning curve getting this to even install hahaha :D  
for anyone who wants to achieve what we all have here - a firmware that will be wiped by google on connection to the internet.... here is my instructions:
make a cable:
get a usb a to usb a extension lead, cut the end off it. get a usb c lead, cut the end of that. wire the usb a lead and the usb c lead together, joining sheild and black together, red and red, green and green, white and white. you will now have a long usb a to usb c lead with a socket in the middle. 

plug the usb c end in the google wifi.
plug your onhub formatted usb key with gale.bin image into your usb a socket. 
hold down the reset button on the google wifi
plug in the usb a plug to a 1.5-2amp supply
hold down the reset button until the google wifi flashes YELLOW AND ORANGE 
hit the developer switch and device reboots 
when it flashes purple, hit it again
lights out, leave it for 5 min or so till it finishes installing. 


congrats - now you have galeforce, don't plug it into the internet or google will wipe it! :D

**Comment by 3boysdad** [comment]
...which is fine...i'd actually prefer to roll it back, which i've honestly been unable to do.  also for those that aren't great with wire/solder -> https://smile.amazon.com/dp/B078HZGWYX/ref=cm_sw_em_r_mt_dp_U_UwGlDbS1KAV6B   this would be your best choice for a powered USB-C connector.

**Comment by exitdown** [comment]
I've tried building with newer versions of stuff but theres some problems with ssh, i think there's been some changes to dropbear etc, i think when i next get some time unless someone else wants to do it it might be worth sniffing traffic on a "legit" device to see what google does to interrogate version etc. It might be horrendously poor practice but we might be able to "lie" about the version depending what it checks.... failing that might have to look at preventing connections to the download server...

**Comment by handwiper** [comment]
Best options:
Flash galeforce. Don’t connect to the internet
Ssh. Find the update code in the firmware and delete.

Or

Block connections to the update server after a sniff. 

However, blocking that update server may just cause the google Wifi app to stop working or certain functions not available or it may not let you set it up at all, based on some checks in the gwifi fware.

Only way to find out is to try..

**Comment by handwiper** [comment]
Too bad the developer dropped off the face of the earth, I know he spent a lot of time and coding to get GF to stick through updates.

**Comment by exitdown** [comment]
well there is a fork thats got active commits (im built on the fork version) https://github.com/Geczy/galeforce so maby we still have some hope hahah :D

**Comment by 3boysdad** [comment]
@handwiper - maybe i'm following (it is early right now) but what would be the point exactly of going that route?  i mean it seems you'd have a device, who's stated purpose is to provide internet connectivity and some security protection, that is effectively powered paperweight that blinks pretty purple and yellow/orange colors at you?

**Comment by exitdown** [comment]
the point is if we cant make the device survive update we need to prevent the device updating. theres various ways to do this each of which may or may not work and may have unintended consequences... im not very experienced at this stuff so im the worst person to be doing this but if i have any success ill definitely share my findings. I have yet to get ssh to work at all ( of course im building on modern versions of busybox etc which have clearly changed and im doing something wrong no doubt) ill log an issue on Geczy fork too in case he hasnt noticed - but i suspect he will have lol

**Comment by IMS212** [comment]
Any luck? @exitdown

**Comment by exitdown** [comment]
i've actually been preoccupied with car stuff :) so I havn't had a chance to try yet. will advise when i do if i manage to solve anything though!

**Comment by exitdown** [comment]
i dont have any progress to report but i do have some bad news - i was able to get some information from a reliable source, this firmware overwrite was not done because google 'wanted' to - it was done because the fcc told them to out of concern that people could violate radio spectrum regulations using this firmware. what that means in practice is that it will be cat and mouse for anything that is built against google software - so any alternate firmwares from this point will need to be essentially decoupled from google to prevent overwrites. obviously that means configuration will need to be handled manually too. its a shame but there it is.

**Comment by 3boysdad** [comment]
while this is a bummer, sadly it left one of my pucks bricked with one their updates.

**Comment by exitdown** [comment]
you should be able to fix that by downloading the official onhub image and flashing it using the same process you used for installing galeforce

**Comment by 3boysdad** [comment]
yep...tried that few times. works for a few days then inexplicably stops.  even moved it from being my 'primary'.  was rather frustrated with them - while I still have two of them, i'll probably ditch them this next year.  a rather disappointing $300USD purchase I've made in long time.
