### ISSUE TITLE
Question: Is this project still valid?

### ISSUE THREAD

**Issue by bdmorin** [marcosscriven/galeforce#44]
Sometimes projects don't need to be updated,and they work fine. I'm curious if this still works? Does the project require updates for it to keep working? I see the build is passing, but I have no idea if that's going from current google hardware updates.

Thanks!

**Comment by IMS212** [comment]
It does work, but connecting to the internet is impossible because google patched the update function causing GaleForce to be removed, or soft-brick the device (reset needed)

**Comment by bdmorin** [comment]
Thank you!
