### ISSUE TITLE
2019-10-03 Bricked WiFi Puck

### ISSUE THREAD

**Issue by sfc-gh-gpavlik** [marcosscriven/galeforce#45]
The procedures and code in this project no longer seem to work with the current firmware release from Google. It bricked one of my WiFi pucks, which is no great loss since Google dumbed down the firmware to the point of being silly. The remaining pucks are in bridge mode and I bought a router for grownups.

Thank you for the effort on this project. It was definitely worth a try to get past the useless Google firmware.

**Comment by user747** [comment]
Bricking always a risk flashing. Did you use this fork https://github.com/Geczy/galeforce which has slightly more recent commits ? 

Readme needs an update at the top with something like " Update 2019 - repo no longer maintained, do not use. Keeping available for education and or future forks" 

Time to grab some Rpi 4's, wifi dongles , openwrt, and batman.

**Comment by magic-madrigal** [comment]
I wasn’t able to get either repo to work, but was able to restore to the
original firmware using Google Restore tool.
