### ISSUE TITLE
Is this still usable?

### ISSUE THREAD

**Issue by aaronjspeed** [marcosscriven/galeforce#46]
I’m trying to gain root access. Is this project still viable?

**Comment by IMS212** [comment]
Couldn’t get google WiFi to turn on at all after flash, it seems like newer updates brick and/or overwrite galeforce

**Comment by StruggleBuddies** [comment]
> Couldn’t get google WiFi to turn on at all after flash, it seems like newer updates brick and/or overwrite galeforce

Use the Google Restore Tool to restore the firmware on the puck if you have any more issues.

**Comment by IMS212** [comment]
Yeah, bricks mine too. Guess this is dead after all
