### ISSUE TITLE
galeforce functionality examples

### ISSUE THREAD

**Issue by msturgill** [marcosscriven/galeforce#5]
It would be helpful if the readme expanded on some of the additional functionality possible using galeforce.

Examples:

Is it possible to enable mesh in bridge mode (or bridge in normal mode, eliminating double NAT)?

Can the default IP address range be changed? How are these settings made persistent?

Are sample instructions available to run OpenVPN or establish an IKEv2 IPSec VPN?

**Comment by dixnor** [comment]
Yes, I second that. Instructions or Wiki will be really helpful.

**Comment by marcosscriven** [comment]
I've been on vacation this week, but I'll see what I can cook up one evening next week.

In short, the answer is yes to all your questions. You essentially have a Gentoo-flavoured Linux system, so Googling how to set such things up in that context will help you. 

My personal motivations were:

1. Seeing what's up with dnsmasq
2. DDNS client
3. OpenVPN

The only real challenge is making it persist between updates, as the entire root is rewritten and toggled. See [galeforce.conf](https://github.com/marcosscriven/galeforce/blob/master/galeforce/conf/galeforce.conf) for an example. There is a so-called stateful partition where you can put stuff like this, with various mount points (/var and /usr/local for example)

Regarding specifics, what you want to look at is the various ```/etc/init/ap_*``` conf files. 

I was considering building on Galeforce a little to make this easier, but wondered if a target audience even existed? I thought perhaps the people that would want root access might want to do things their own way.

**Comment by msturgill** [comment]
Thank you for the reply!

I agree with your assertion that the target audience is probably fairly advanced. Documenting some of the nuances of the platform and showing a few examples of what is possible would go a long way though.

Even the notes in your reply are a great starting point (Gentoo based, ap_* config files, /var and /usr/local being stateful, galeforce.conf for an init example).

**Comment by surge919** [comment]
Does this work on the Asus OnHub?

My main desire is to enable mesh while in bridge mode.  Above you said Yes to all, so I'm interested in trying this out.

thanks

**Comment by marcosscriven** [comment]
@surge919 - it should do, but I've no way to test it. Change the board name [here](https://github.com/marcosscriven/galeforce/blob/master/bin/build-image.sh#L13) to ```arkham```.

**Comment by dixnor** [comment]
Thanks for the update @marcosscriven and yes you are right saying that the target audience is limited. My main motivation in fact by rooting this little guy is to be able to change the local network ip subnet. Could not believe it that this option is not available on native firmware, a basic option for me.

**Comment by mdlima** [comment]
Have anyone tried using the bluetooth? My idea is to track bluetooth keychains using Google Wifi, as they're spread throughout the house.

**Comment by Noosnom** [comment]
Thanks for this great project, I can't wait to try it out. I don't have much of a background in this field, though your instructions seem easy enough to follow. Would you be able to give me some hints what to do in order to set up a built-in VPN?

**Comment by ericpulvino** [comment]
I'm curious to understand the default setup... i.e. is there a routing protocol of some kind like babel running here? Can I tweak vlan assignment of different connected devices etc?

**Comment by tcjtomas** [comment]
What would be very interessting:
Make the GWF a router eg. disable NAT. adding DHCP relay. Forwarding broadcast from smb and google printing in local mode.

**Comment by myusuf3** [comment]
@marcosscriven I am in dire need of setting up mesh network in bridge mode so i can assign routing to my ERX from unifi. Would love to hear your thoughts.
