### ISSUE TITLE
AP Controller Settings

### ISSUE THREAD

**Issue by biscuitehh** [marcosscriven/galeforce#6]
Where is the best place to override `SETTING_DHCP_GUEST_END` and similar settings that relate to the IP of the router? I know `ap-controller.conf` creates a "stateless root" where it will load the stored settings of the AP. However, I can't seem to source where it decides to pick the IP ranges that are used. Any help with this would be appreciated - this project is a lifesaver so far!

**Comment by dixnor** [comment]
This is what I am looking for, modify the ip range. If you figure out where this setting is done, please let us now. Thanks
