### ISSUE TITLE
Select 5ghz channel / enable it

### ISSUE THREAD

**Issue by saprette** [marcosscriven/galeforce#9]
Hello,

I bought my Google WiFi in the US but I'm using it in France now. 
Because of this country change, my Google WiFi doesn't create the 5ghz signal anyone, because it's an US model and channel regulation is different in Europe. Do you think I could use galeforce to configure the state / channel of the 5ghz signal?

**Comment by stab72** [comment]
Hi, I am having the same issue in Greece. So I am looking for a similar solution. It would be great if through galeforce we can configure the channels available on the 5 GHz channel.
Thanks

**Comment by thomaswatnedal** [comment]
I also bough it in the US and deployed it in Norway, with the same result: No 5 Ghz wifi on most devices. The wifi was using channel 149 which has different usage in Europe than in the US.

It might be possible to change this using the iw command? Optionally it *might* be possible to flash the device with firmware from another region. I have not looked into this though.

**Comment by wherzig** [comment]
I have had the same problem after I bought a 3pack of Google Wifi in the US. After some investigations I found the solution. The hardware of the US model (NLS-1304-25) and the European model (AC-1304)  has just different firmware on the router but has the same hardware as expected.

The primary Wifi point (the one connected to the modem or internet CPE router)) distributes software and configuration to the other wifi points. If you have an European wifi point (AC-1304) as the primary wifi point then all attached wifi points will work on european frequences. Even US models.

So alll to get your US models work ist just to buy a single European Google wifi point and install it as the primary. With this I have now 5 wifi points running. Two European and three US models. They all work like the european models.

**Comment by simenbrekken** [comment]
I’m curious what happens if you make one of the “slaves” the master afterwards. Will they still keep the new region or revert to their previous settings?

Ordered another node now, hopefully it will fix my 5ghz country related issues.

**Comment by thomaswatnedal** [comment]
I can also confirm that setting a European node as master makes them all use the European channels. Actually my American nodes also show up as AC-1304.

**Comment by wherzig** [comment]
@simenbrekken Yes, if the master is European, the US nodes will also set to the European region. At least this works for me. Just try. If it does not work, just send the node back to Google and you will get your money back;-)

**Comment by simenbrekken** [comment]
I tried verifying what @thomaswatnedal and @wherzig have experienced today, but alas my American nodes are still born in the USA:

1. Factory reset all my US nodes
2. Unboxed my new EU/NO node and set it up fresh:

<img width="1152" alt="fresh-node" src="https://user-images.githubusercontent.com/12807/32821636-b8b887c0-c9d4-11e7-831c-79fcac770e5d.png">

_As you can see it's broadcasting country code `nl`_

3. Added one of my factory reset US nodes and let it stay for a while hoping it might be assimilated (Even tried unplugging it for a while and adding it back in):

<img width="1155" alt="added-us-node" src="https://user-images.githubusercontent.com/12807/32821691-048da7ca-c9d5-11e7-9742-b9c677d12dbf.png">

_The EU node is still broadcasting country code `nl` but my US node is still broadcasting `us`_

Can any of you guys run a Wifi scan and verify your US nodes are not broadcasting `us`? I'm beginning to think that child nodes receive channel assignments from the master which is EU regulated but still broadcasting their original country code. If this is the case, it's still a problem for a lot of Apple products as they reconfigure available bands (in particular 5ghz bands) as soon as they receive a country code from a seen WiFi device via [IEEE_802.11d](https://en.wikipedia.org/wiki/IEEE_802.11d-2001)

Another theory is that they'll become EU nodes as soon as there's another software update.

**Comment by thomaswatnedal** [comment]
> Can any of you guys run a Wifi scan and verify your US nodes are not broadcasting us?

My US nodes also still says country code US, while my European one says NL, as yours.

> I'm beginning to think that child nodes receive channel assignments from the master which is EU regulated but still broadcasting their original country code.

Seems to be true.

> If this is the case, it's still a problem for a lot of Apple products as they reconfigure available bands (in particular 5ghz bands) as soon as they receive a country code from a seen WiFi device via IEEE_802.11d

The channels are chosen by the access point(s), so regardless of which country code they broadcast the clients will have to use the channels provided. In this case if the master is a EU node, and chooses the channel also for the slaves, I don't think it is a problem. Most of the EU channels are also valid for the US so even if a device would restrict itself it is likely to work,.

All my nodes report the same: (from the report available at http://NODEIP/api/v1/diagnostic-report)

Interface wlan-5000mhz
  ifindex 9
  wdev 0x100000001
  addr 703acb000013     
  ssid YourSSID
  type AP
  channel 36 (5180 MHz), width: 80 MHz, center1: 5210 MHz

**Comment by wherzig** [comment]
Which operating systems use IEEE_802.11d? I do not use Apple devices.
How can this be shown on non Apple devices?

Looking at Windows wifi monitoring tools and Linux (iwlist scan) there seem to be no difference between my US and EU nodes. Frequences, etc. are all the same. Wifi works fine with Linux, Android and Windows devices.

If  IEEE_802.11d beaconing will cause any problems the solution may be to flash the wifi nodes with new firmware using the recovery mode:

https://support.google.com/wifi/answer/6274977?hl=en-GB

Anyone tried that? I did not try it because I do not have the USB-C adapter with Power Delivery that Marcos Scriven decibed doing his firmware changes here at github.

**Comment by simenbrekken** [comment]
@thomaswatnedal Seems to work so far, but I've had problems keeping my MacBook online as everytime it has woken up in the past it receives the US country code and 5ghz stops working. Fingers 🤞

@wherzig Not sure how to scan for router regulatory country configuration on Windows, so I can't help you out there. That last link looks very interesting. I'll try to flash one of my US nodes this weekends and get back to you.

**Comment by wherzig** [comment]
How to see regulatory country code on non Apple operating systems like Linux or Android?

**Comment by simenbrekken** [comment]
After running the EU/NO primary/US secondary setup this weekend all problems with devices presumably configured for NO bands and thus not being able to connect to channels selected by my then US regulated primary Google Wifi node has disappeared.

The primary node sets channels (both 2.4 and 5 ghz) for all other nodes in the mesh configuration, no matter what country regulation setting they are currently configured as.

@wherzig As this is finally working, I'm going to hold off flashing any of my US nodes.

**Comment by mak1238** [comment]
@simenbrekken What application is that that shows you the countrycode?

Also, in general, I am using US Google Wifi here in Europe, and it works just fine out of the box, also on 5 GHz. What problems are you guys having? I did select US as country code when setting up and am using a US Google account, so I suppose it doesn't "know" I am not in USA.
What other frequencies do EU versions use then, or are there just less? All I know is that on 2.4 GHz channels 12 and 13 are not available in the US, but that's not a great problem in Europe.

I just checked and my 2.4 is running on channel 5 while the 5 GHz is running on channel 149 - AFAIK both are allowed in Europe and all devices support them.

**Comment by bogorad** [comment]
I have the same problem. Two US google wifi units, in Spain. Channel 149. MS Surface Pro 3 (US model) works fine. Pixel-1 (US model) without a SIM card works fine. 

Pixel-2XL (US model) with a Spanish SIM card (Vodafone.es) ignores 5GHz. Now I remove the SIM, and do airplane mode on+off. The phone immediately sees 5GHz. Put it back - 5GHz is gone.

**Comment by cnc79** [comment]
Hey guys same issue on my end.. and i am in Mauritius... any progress on this :)

**Comment by uzzitm** [comment]
Hey guys, any solution to change the 5GHz channel for the US models from ssh? For the rest of us who don't want to buy a 4th puck from the EU. Thanks !

**Comment by bogorad** [comment]
> any solution to change the 5GHz channel for the US models 

Nope, I swapped my second one with a friend :)
